### ISSUE TITLE
empty screen via https reverse proxy - websocket problem

### ISSUE THREAD

**Issue by mamema** [m-bers/docker-virt-manager#5]
as soon as a reverse proxy HAPROXY or nginx for example come into play, a wss:// connection will tried to be opened by the proxy, which fails (websocket not working)

Browser errors out with "cannot open connection to wss://www.example.com/socket

400 Bad websocket request

**Comment by core2duoe6420** [comment]
I met with this problem too. After several hours of traffic capturing, comparison and debug, I believe the root cause of this issue is a bug in `broadwayd`. It only recognizes header `Sec-WebSocket-Key` via case sensitive comparison. If proxy sends anything like `Sec-Websocket-Key` (note the lowercase `s`), then `broadwayd` returns a `400 Bad websocket request`.

I make a workaround by adding one line `proxy_set_header Sec-WebSocket-Key $http_sec_websocket_key;` in `/etc/nginx/nginx.tmpl`. Hope this can help.

**Comment by mamema** [comment]
Great find!
This works
Thanks

**Comment by m-bers** [comment]
@core2duoe6420 submit a PR and I'll merge it.

**Comment by owenthewizard** [comment]
I'm having this issue as well using Cloudflare Tunnel. Any help would be appreciated.

Headers when retrieved via Cloudflare:
```js
await fetch("wss://virt-manager.walpole.dev/socket", {
    "credentials": "include",
    "headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0",
        "Accept": "*/*",
        "Accept-Language": "en-US,en;q=0.5",
        "Sec-WebSocket-Version": "13",
        "Sec-WebSocket-Protocol": "broadway",
        "Sec-WebSocket-Extensions": "permessage-deflate",
        "Sec-WebSocket-Key": "REDACTED",
        Sec-Fetch-Dest": "websocket",
        "Sec-Fetch-Mode": "websocket",
        "Sec-Fetch-Site": "same-origin
        "Pragma": "no-cache",
        "Cache-Control": "no-cache"
    },
    "method": "GET",
    "mode": "cors"
});
```

Header when retrieved on LAN:
```js
await fetch("wss://virt-manager.walpole.dev/socket", {
    "credentials": "omit",
    "headers": {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0",
        "Accept": "*/*",
        "Accept-Language": "en-US,en;q=0.5",
        "Sec-WebSocket-Version": "13",
        "Sec-WebSocket-Protocol": "broadway",
        "Sec-WebSocket-Extensions": "permessage-deflate",
        "Sec-WebSocket-Key": "REDACTED",
        "Pragma": "no-cache",
        "Cache-Control": "no-cache"
    },
    "method": "GET",
    "mode": "cors"
});
```

Notice...
```
"Sec-Fetch-Dest": "websocket",
"Sec-Fetch-Mode": "websocket",
"Sec-Fetch-Site": "same-origin
```

...are only sent with Cloudflare.

**Comment by owenthewizard** [comment]
I tested with https://github.com/m-bers/broadway-baseimage as well as my own custom broadway image and this seems to be an issue with broadway.
